//! NV method-header decoder and dispatch-table scaffold.
//!
//! PS3 RSX consumes a FIFO of 32-bit command words. Each word is either
//! a method header followed by argument dwords, or a control-flow
//! command (jump / call / return). The advance pass reads one word at
//! a time, decodes it via [`decode_header`], consumes the declared
//! argument count, and either dispatches a registered handler or falls
//! back to the unknown-method warning path.
//!
//! ### Provenance
//!
//! The PS3's RSX is a variant of Nvidia's NV40 / G71 GPU family, and
//! the FIFO command encoding used here is the same NV2A / NV4097
//! command format documented by open-source reverse engineering
//! (Nouveau, envytools) and reimplemented in RPCS3.
//!
//! - **Command-type flag bits** (NON_INCREMENT, JUMP, CALL, RETURN)
//!   and the **11-bit count field at bit 18** are NV2A-generation
//!   hardware conventions that predate the PS3 and are documented
//!   in Nouveau's `envytools` (MIT-licensed) and RPCS3's
//!   `Emu/RSX/gcm_enums.h` (GPL-3.0).
//! - **NV406E and NV4097 method addresses** (SET_REFERENCE,
//!   SEMAPHORE_OFFSET, SEMAPHORE_RELEASE, NO_OPERATION,
//!   GET_REPORT) are taken from RPCS3's `Emu/RSX/nv406e.h` /
//!   `nv4097.h` which in turn follow Nouveau's register
//!   specifications.
//! - **GCM_FLIP_COMMAND** (`0xFEAC`) is a Sony-specific extension
//!   not present in upstream Nvidia hardware; it is taken from
//!   RPCS3's `Emu/RSX/gcm_enums.h` (`GCM_FLIP_COMMAND =
//!   0x0000FEAC >> 2`) where it has been present since the early
//!   RPCS3 RSX work.
//!
//! ### Method-address field
//!
//! The 14-bit method address field occupies bits 2..=15 of the raw
//! word, with the bottom two bits always zero because RSX method
//! addresses are 4-byte aligned. The NV2A hardware also packs a
//! 3-bit subchannel into bits 13..=15, but Sony's libgcm exposes
//! methods as a flat 14-bit address space via symbolic constants,
//! so our decoder follows the same flat-address convention: the
//! dispatch table keys on the full 14-bit method byte address.
//!
//! ### Endianness
//!
//! FIFO memory is little-endian u32 from the RSX's perspective.
//! The PS3's PPU is big-endian, so libgcm byte-swaps command
//! words before writing them. The advance pass reads raw LE
//! bytes and this module operates on already-deswapped
//! host-endian u32 values.

use crate::rsx::RsxFifoCursor;
use cellgov_effects::Effect;
use cellgov_time::GuestTicks;
use std::collections::BTreeMap;

/// Bit 30: when set, the method header is non-incrementing (all
/// args write to the same method address). NV2A hardware
/// convention; RPCS3 documents this as its
/// `RSX_METHOD_NON_INCREMENT_CMD`.
pub const NV_FLAG_NON_INCREMENT: u32 = 0x4000_0000;

/// Bit 29: the RSX's original JUMP form (absolute jump to a FIFO
/// byte address in bits 2..=28). RPCS3 documents this as its
/// `RSX_METHOD_OLD_JUMP_CMD`; envytools describes the same
/// encoding for the NV2A FIFO engine.
pub const NV_FLAG_JUMP: u32 = 0x2000_0000;

/// Bit 1: subroutine CALL. Offset in bits 2..=28. RPCS3
/// documents this as its `RSX_METHOD_CALL_CMD`.
pub const NV_FLAG_CALL: u32 = 0x0000_0002;

/// Bit 17: subroutine RETURN. Rest of the word is zero. RPCS3
/// documents this as its `RSX_METHOD_RETURN_CMD`.
pub const NV_FLAG_RETURN: u32 = 0x0002_0000;

/// Bit 0 set alone: RPCS3 classifies this as a "new" JUMP
/// encoding with a 30-bit offset (mask `0xFFFFFFFC`).
/// Documented in RPCS3's `Emu/RSX/gcm_enums.h` as
/// `RSX_METHOD_NEW_JUMP_CMD`. Real game FIFOs in the RPCS3
/// trace corpus almost always use the old form; we recognise
/// the new form defensively.
pub const NV_FLAG_NEW_JUMP: u32 = 0x0000_0001;

/// Shift for the 11-bit method count field. NV2A hardware
/// convention (count occupies bits 18..=28).
pub const NV_COUNT_SHIFT: u32 = 18;

/// Width of the method count field. The NV2A hardware caps the
/// count at 2047 (11 bits); values outside this range are not
/// generated by a compliant FIFO writer.
pub const NV_COUNT_MASK_11: u32 = 0x7FF;

/// Mask for the 14-bit method address field (bits 2..=15). The
/// bottom two bits are always zero because RSX method addresses
/// are 4-byte aligned (word-granular write targets), so any
/// stray low bits are dropped at decode time.
pub const NV_METHOD_MASK: u32 = 0x0000_FFFC;

/// Mask for the union of all non-normal-method bits. Used ONLY as
/// the final catch-all after every control-flow classifier has
/// failed: if any of these bits are still set, the header is
/// malformed. RPCS3 calls this `RSX_METHOD_NON_METHOD_CMD_MASK`;
/// no direct Sony name.
///
/// Contents: bits 0 (NEW_JUMP), 1 (CALL), 16 (reserved companion
/// of RETURN's bit 17), 17 (RETURN), 29 (OLD JUMP), 31 (reserved).
/// Bit 30 (NON_INCREMENT) is a normal-method modifier and is
/// deliberately NOT in this mask. Bits 2..=15 (method address)
/// and 18..=28 (count) are normal-method fields. Bit 16 appears
/// here because RPCS3 tracks it alongside RETURN in its equivalent
/// `RSX_METHOD_NON_METHOD_CMD_MASK`; a set bit 16 alone would
/// otherwise fall through to the normal-method path and produce
/// a bogus method address, so the catch-all catches it.
const NON_METHOD_MASK: u32 =
    0x8000_0000 | NV_FLAG_JUMP | NV_FLAG_RETURN | 0x0001_0000 | NV_FLAG_NEW_JUMP | NV_FLAG_CALL;

/// Offset mask for the old-JUMP offset field (bits 2..=28).
pub const NV_OLD_JUMP_OFFSET_MASK: u32 = 0x1FFF_FFFC;

/// Offset mask for the new-JUMP offset field (bits 2..=31).
pub const NV_NEW_JUMP_OFFSET_MASK: u32 = 0xFFFF_FFFC;

/// Offset mask for the CALL offset field (bits 2..=28).
pub const NV_CALL_OFFSET_MASK: u32 = 0x1FFF_FFFC;

/// NV406E SET_REFERENCE (`0x0050`). Source: RPCS3's
/// `Emu/RSX/nv406e.h`. Writes the argument to the control
/// register's reference slot. Emitted by the Sony libgcm
/// `cellGcmSetReferenceCommand` function; guests observe the
/// value by reading the RSX control register's reference slot
/// directly at [`crate::rsx::RSX_CONTROL_REF_ADDR`] (Sony's
/// libgcm has no `cellGcmGetCurrentReference` NID).
pub const NV406E_SET_REFERENCE: u16 = 0x0050;

/// NV406E SEMAPHORE_OFFSET (`0x0064`). Source: RPCS3's
/// `Emu/RSX/nv406e.h`. Stores the label-area offset that the
/// next SEMAPHORE_RELEASE writes to.
pub const NV406E_SEMAPHORE_OFFSET: u16 = 0x0064;

/// NV406E SEMAPHORE_ACQUIRE (`0x0068`). Source: RPCS3's
/// `Emu/RSX/nv406e.h`. Waits for the label at the stored offset
/// to match the argument value. Not on the current handler
/// list; documented for future reference.
pub const NV406E_SEMAPHORE_ACQUIRE: u16 = 0x0068;

/// NV406E SEMAPHORE_RELEASE (`0x006C`). Source: RPCS3's
/// `Emu/RSX/nv406e.h`. Writes the argument value to the label-
/// area offset stored by the prior SEMAPHORE_OFFSET method.
pub const NV406E_SEMAPHORE_RELEASE: u16 = 0x006C;

/// NV4097 NO_OPERATION (`0x0100`). Source: RPCS3's
/// `Emu/RSX/nv4097.h`. No-op method with one argument (always
/// zero).
pub const NV4097_NO_OPERATION: u16 = 0x0100;

/// NV4097 GET_REPORT (`0x1800`). Source: RPCS3's
/// `Emu/RSX/nv4097.h`. Writes a report value (type + timestamp)
/// to the report destination. RPCS3's source uses the name
/// `NV4097_GET_REPORT`, reflecting that the guest later retrieves
/// (gets) the report value; some Nvidia-world documentation calls
/// the same method `SET_REPORT` from the GPU's emit-time
/// perspective. We use GET_REPORT for consistency with RPCS3.
pub const NV4097_GET_REPORT: u16 = 0x1800;

/// NV4097 SET_SEMAPHORE_OFFSET (`0x1D6C`). Source: RPCS3
/// `Emu/RSX/gcm_enums.h:696`
/// (`NV4097_SET_SEMAPHORE_OFFSET = 0x00001d6c >> 2`). The
/// back-end-pipeline companion of [`NV406E_SEMAPHORE_OFFSET`]:
/// the guest emits this to stage a label offset for a subsequent
/// [`NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE`]. Emitted by
/// libgcm's inline `cellGcmSetWriteBackEndLabel` helper. Behaves
/// identically to the NV406E variant for CPU-visible completion
/// purposes (the oracle does not model the pipeline-stage
/// distinction).
pub const NV4097_SET_SEMAPHORE_OFFSET: u16 = 0x1D6C;

/// NV4097 BACK_END_WRITE_SEMAPHORE_RELEASE (`0x1D70`). Source:
/// RPCS3 `Emu/RSX/gcm_enums.h:697`
/// (`NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE = 0x00001d70 >> 2`).
/// Emitted by libgcm's inline `cellGcmSetWriteBackEndLabel`
/// helper after a byte-0 / byte-2 pre-swap of the value. Real PS3
/// GPU undoes the swap in its back-end semaphore path (see
/// RPCS3's `Emu/RSX/rsx_methods.cpp` `back_end_write_semaphore_release`
/// handler at line 1623+), so the final CPU-visible label value
/// matches what the guest intended to write, not the pre-swap
/// word in the FIFO. The handler applies the inverse swap to
/// reproduce the guest-visible outcome.
pub const NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE: u16 = 0x1D70;

/// GCM_FLIP_COMMAND (`0xFEAC`). Source: RPCS3's
/// `Emu/RSX/gcm_enums.h` (defined as
/// `GCM_FLIP_COMMAND = 0x0000FEAC >> 2` -- dword-index form;
/// byte-address form is `0xFEAC`). RPCS3 has carried this value
/// since early RSX work. Emitted by the PS3-specific
/// `cellGcmSetFlip` to trigger a framebuffer flip; argument is
/// the display-buffer id.
pub const GCM_FLIP_COMMAND: u16 = 0xFEAC;

/// A decoded command-class classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NvCommandKind {
    /// Normal incrementing method. Each argument increments the
    /// effective method address by 4.
    Increment,
    /// Non-incrementing method. All arguments write to the same
    /// method address. Observed in retail FIFO streams primarily
    /// around DrawIndexArray emission; defensive modelling treats
    /// any guest-emitted non-increment header as well-formed.
    NonIncrement,
    /// Sony's old JUMP form. Jump target is 29-bit-offset byte
    /// address (4-aligned).
    Jump {
        /// Target byte address (4-aligned) masked to 29 bits.
        offset: u32,
    },
    /// RPCS3's "new" JUMP form. Jump target is 30-bit-offset
    /// byte address. Defensive; libgcm does not emit this.
    NewJump {
        /// Target byte address (4-aligned) masked to 30 bits.
        offset: u32,
    },
    /// Subroutine CALL. Return address is pushed onto the RSX
    /// call stack; see NV_CALL_OFFSET_MASK.
    Call {
        /// Target byte address (4-aligned) masked to 29 bits.
        offset: u32,
    },
    /// Subroutine RETURN.
    Return,
    /// Header that failed every recognised pattern. Primary
    /// examples: bit 31 set alone (reserved), RETURN flag with
    /// stray method-address bits, or a combination of bits that
    /// does not match the (generous, hardware-matching) masks for
    /// RETURN / CALL / NEW_JUMP / OLD JUMP.
    ///
    /// The raw word is preserved verbatim so that a downstream
    /// diagnostic can recover the exact bit pattern -- the
    /// recognised-flag subset alone is insufficient to explain
    /// what went wrong, because a RETURN with garbage and a
    /// hypothetical future reserved-bit combination both surface
    /// here.
    Malformed {
        /// Raw 32-bit FIFO word preserved intact so diagnostics
        /// can distinguish cause classes (e.g. RETURN+method vs
        /// bit-31-alone vs multi-flag after every check failed).
        raw: u32,
    },
}

/// Decoded NV method header.
///
/// `method` and `count` are meaningful only for `Increment` and
/// `NonIncrement` kinds; control-flow variants leave them zero.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct NvMethodHeader {
    /// Command classification from the flag bits.
    pub kind: NvCommandKind,
    /// Method byte address (bits 2..=15 of the raw word, bottom
    /// two bits always zero). Zero for control-flow kinds.
    pub method: u16,
    /// Number of 32-bit argument dwords following this header
    /// in the FIFO stream (0..=2047). Zero for control-flow kinds.
    pub count: u16,
}

impl NvMethodHeader {
    /// Construct an increment / non-increment normal-method header.
    #[inline]
    const fn normal(kind: NvCommandKind, method: u16, count: u16) -> Self {
        Self {
            kind,
            method,
            count,
        }
    }

    /// Construct a control-flow or nop header; method and count are
    /// forced to zero because they have no meaning for these kinds.
    #[inline]
    const fn control(kind: NvCommandKind) -> Self {
        Self {
            kind,
            method: 0,
            count: 0,
        }
    }
}

/// Decode a raw FIFO word (already-deswapped, host-endian u32) into
/// a structured header.
///
/// ### Classification order and hardware-matching trade-off
///
/// The decoder matches RPCS3 and the NV2A hardware: each control-flow
/// form is identified by a specific bit pattern, and the first
/// matching check wins. The classification masks are Sony's
/// `CELL_GCM_METHOD_FLAG_*` values combined with RPCS3-documented
/// per-form masks:
///
/// - RETURN first, strict exact match (`cmd == 0x00020000`). Any
///   stray method-address or count bits alongside RETURN take the
///   malformed path -- this is stricter than RPCS3's loose RETURN
///   mask. The asymmetry with CALL / JUMP / NEW_JUMP is
///   deliberate: RETURN has no offset or argument field, so every
///   bit outside bit 17 is unambiguously garbage and there is no
///   legitimate value we would reject by being strict. CALL /
///   JUMP / NEW_JUMP all carry wide offset fields (bits 2..=28
///   or 2..=31), so strict classification there would reject
///   valid offsets whose bits happened to overlap other flag
///   positions. Being strict only where there is nothing legitimate
///   to reject is the principle that makes this asymmetry safe.
/// - CALL next: bits 0..=1 == `0b10`. Hardware ignores bits 2..=31
///   beyond the offset, so extra flag bits in a CALL word are
///   silently folded into the offset rather than flagged. This
///   matches RPCS3's `(cmd & 0x3) == RSX_METHOD_CALL_CMD` check.
/// - NEW_JUMP: `(cmd & 0xe0000003) == 0x1` -- bits 0..=1 == `0b01`
///   with bits 29..=31 clear.
/// - OLD JUMP: `(cmd & 0xe0000003) == 0x20000000` -- bit 29 set
///   with bits 0..=1, 30..=31 clear.
/// - Otherwise, if any NON_METHOD_MASK bit is set, Malformed.
/// - Otherwise, normal method; bit 30 selects Increment vs
///   NonIncrement, bits 2..=15 are the method address, bits
///   18..=28 are the count.
///
/// **Multi-flag combinations match the first-recognised form.** A
/// word with both CALL and JUMP bits set is classified as CALL
/// because CALL is checked before JUMP -- the JUMP bit is silently
/// folded into the CALL offset. This matches real NV2A FIFO
/// behaviour and keeps cross-runner comparison against RPCS3
/// byte-identical on pathological inputs. Stricter classification
/// would correctly flag guest-side corruption but would diverge
/// from RPCS3; we rely on other oracle machinery (per-step state
/// hashing, cross-runner observation comparison) to catch
/// corruption-class bugs instead.
///
/// ### Arity not enforced
///
/// `count` is returned verbatim from bits 18..=28. The decoder does
/// NOT know how many arguments each method actually expects. A
/// header like `CELL_GCM_METHOD(NV4097_GET_REPORT, 0)` decodes
/// cleanly with `count == 0` even though the method semantically
/// requires one argument. Per-method arity validation is a handler
/// responsibility, not the decoder's. Handlers receive the full
/// argument slice and may reject an unexpected length.
///
/// Similarly, a NonIncrement header with `count == 0` is
/// structurally well-formed and decodes without warning. Sony
/// restricts NonIncrement to DrawIndexArray but does not encode
/// that restriction in the FIFO format; guests that emit
/// zero-count NonIncrement headers are misusing the ABI, and the
/// advance pass treats them as no-ops (zero args consumed).
pub const fn decode_header(cmd: u32) -> NvMethodHeader {
    // RETURN: strict exact match. Any stray method / count bits
    // take the malformed path below.
    if cmd == NV_FLAG_RETURN {
        return NvMethodHeader::control(NvCommandKind::Return);
    }
    // CALL: bits 0..=1 == 0b10. RPCS3 uses mask 0x3 (no restriction
    // on bits 29..=31 or higher offset regions); we match that so
    // a word with extra flag bits decodes as CALL rather than
    // Malformed. See doc note above.
    if (cmd & 0x0000_0003) == NV_FLAG_CALL {
        return NvMethodHeader::control(NvCommandKind::Call {
            offset: cmd & NV_CALL_OFFSET_MASK,
        });
    }
    // NEW_JUMP: bits 0..=1 == 0b01, bits 29..=31 clear.
    if (cmd & 0xE000_0003) == NV_FLAG_NEW_JUMP {
        return NvMethodHeader::control(NvCommandKind::NewJump {
            offset: cmd & NV_NEW_JUMP_OFFSET_MASK,
        });
    }
    // OLD JUMP (Sony's form): bit 29 set, bits 0..=1 and 30..=31
    // clear.
    if (cmd & 0xE000_0003) == NV_FLAG_JUMP {
        return NvMethodHeader::control(NvCommandKind::Jump {
            offset: cmd & NV_OLD_JUMP_OFFSET_MASK,
        });
    }
    // Any remaining NON_METHOD bit set and no control-flow mask
    // matched: malformed. Primarily catches bit 31 set alone
    // (reserved) or bit 17 set alone (RETURN flag with garbage).
    if (cmd & NON_METHOD_MASK) != 0 {
        return NvMethodHeader::control(NvCommandKind::Malformed { raw: cmd });
    }
    // Normal method: bit 30 distinguishes INCREMENT / NON_INCREMENT.
    let kind = if (cmd & NV_FLAG_NON_INCREMENT) != 0 {
        NvCommandKind::NonIncrement
    } else {
        NvCommandKind::Increment
    };
    let method = (cmd & NV_METHOD_MASK) as u16;
    let count = ((cmd >> NV_COUNT_SHIFT) & NV_COUNT_MASK_11) as u16;
    NvMethodHeader::normal(kind, method, count)
}

/// Mutable dispatch context handed to every NV method handler.
///
/// Bundles the three pieces of state the RSX method handlers need
/// to read or mutate during a FIFO drain:
///
/// - the cursor (for handlers that write a control-register field
///   such as `current_reference`),
/// - the transient semaphore-offset register (set by
///   `NV406E_SEMAPHORE_OFFSET`, consumed by the next
///   `NV406E_SEMAPHORE_RELEASE`),
/// - the effect sink the drain forwards into the next commit batch.
///
/// All three are borrowed mutably from the runtime; the context is
/// built fresh per-method-call. This mirrors
/// [`crate::commit::CommitContext`]'s shape: one struct with many
/// mutable refs so the handler signature does not widen with every
/// new field.
pub struct NvDispatchContext<'a> {
    /// RSX FIFO cursor. Handlers that update the control register
    /// (e.g. `NV406E_SET_REFERENCE`) mutate fields here; the advance
    /// pass owns `get` mutation and does not grant handlers access
    /// to it through this context.
    pub cursor: &'a mut RsxFifoCursor,
    /// Transient label-write offset. The `NV406E_SEMAPHORE_OFFSET`
    /// handler writes here; the `NV406E_SEMAPHORE_RELEASE` handler
    /// reads it to construct the emitted [`Effect::RsxLabelWrite`].
    /// Folded into the runtime sync-state hash so a forgotten reset
    /// surfaces at the state-hash diff rather than as a silent
    /// cross-drain leak.
    pub sem_offset: &'a mut u32,
    /// Sink for effects the handler asks the drain to forward into
    /// the next commit batch. Pushed in FIFO address order; the
    /// drain preserves that order when it hands effects to the
    /// commit pipeline.
    pub emitted: &'a mut Vec<Effect>,
    /// Current guest-ticks clock at the time of this drain. Used
    /// by handlers whose emitted value depends on the oracle's
    /// monotonic clock (e.g. `NV4097_GET_REPORT` uses it as the
    /// report timestamp). GuestTicks advances by
    /// `result.consumed_cost` per commit; the value here is
    /// frozen for the duration of the drain.
    pub now: GuestTicks,
}

/// Handler signature for a registered NV method.
///
/// Receives the dispatch context (mutable cursor + semaphore
/// offset + effect sink) and the decoded argument slice the advance
/// pass read from the FIFO. Return value is deliberately unit: a
/// handler that needs to report failure does so by emitting a
/// specific effect, not by propagating a `Result`. An invalid-
/// argument handler is a caller-side bug that should be caught in
/// unit tests, not an expected runtime condition.
pub type NvMethodHandler = fn(ctx: &mut NvDispatchContext<'_>, args: &[u32]);

/// `NV406E_SEMAPHORE_OFFSET` handler.
///
/// Stores the sole u32 argument into the transient semaphore-offset
/// register. The next `NV406E_SEMAPHORE_RELEASE` will read it as
/// the target label-area offset. Malformed FIFO streams (zero
/// arguments) leave `sem_offset` unchanged -- the unknown-method
/// fallback is the drain's contract for malformed shapes, not the
/// handler's.
pub fn nv406e_semaphore_offset(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&offset) = args.first() {
        *ctx.sem_offset = offset;
    }
}

/// `NV406E_SEMAPHORE_RELEASE` handler.
///
/// Emits an [`Effect::RsxLabelWrite`] carrying the most recent
/// `sem_offset` and the release value. Pre-handler the guest is
/// expected to have issued an `NV406E_SEMAPHORE_OFFSET`; if it did
/// not, the handler still emits using the current `sem_offset`
/// value (zero after construction) rather than silently dropping
/// the release -- the oracle records the exact CPU-visible outcome
/// of the guest's FIFO stream, including stream bugs.
pub fn nv406e_semaphore_release(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&value) = args.first() {
        ctx.emitted.push(Effect::RsxLabelWrite {
            offset: *ctx.sem_offset,
            value,
        });
    }
}

/// `NV406E_SET_REFERENCE` handler.
///
/// Writes the sole u32 argument into the cursor's
/// `current_reference` field. The guest observes the value by
/// reading the RSX control register's reference slot at
/// [`crate::rsx::RSX_CONTROL_REF_ADDR`]; Sony's libgcm does NOT
/// expose a `cellGcmGetCurrentReference` getter NID (the public
/// API is a direct register read), so no HLE-side companion is
/// needed. Emits no effect -- the reference slot is pure RSX
/// committed state folded into the runtime's sync-state hash via
/// [`crate::rsx::RsxFifoCursor::state_hash`].
pub fn nv406e_set_reference(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&value) = args.first() {
        ctx.cursor.set_reference(value);
    }
}

/// Register the NV406E semaphore offset / release pair into
/// `table` via [`NvMethodTable::register_unique`]. A collision
/// indicates a double-registration bug; callers should propagate
/// the error rather than silencing it.
pub fn register_nv406e_label_handlers(
    table: &mut NvMethodTable,
) -> Result<(), DuplicateRegistration> {
    table.register_unique(NV406E_SEMAPHORE_OFFSET, nv406e_semaphore_offset)?;
    table.register_unique(NV406E_SEMAPHORE_RELEASE, nv406e_semaphore_release)?;
    Ok(())
}

/// Register the `NV406E_SET_REFERENCE` handler into `table`.
/// Separate from [`register_nv406e_label_handlers`] because the
/// reference handler writes the control register's reference slot
/// rather than the label area, and callers that only want label
/// writes should not be forced to adopt reference semantics too.
pub fn register_nv406e_reference_handler(
    table: &mut NvMethodTable,
) -> Result<(), DuplicateRegistration> {
    table.register_unique(NV406E_SET_REFERENCE, nv406e_set_reference)?;
    Ok(())
}

/// `GCM_FLIP_COMMAND` handler (Sony-specific NV4097 flip-buffer
/// method, address `0xFEAC`).
///
/// Emits an [`Effect::RsxFlipRequest`] carrying the low byte of
/// the argument as the buffer index. Real libgcm's
/// `cellGcmSetFlip` packs the display-buffer id (0..=7 in practice)
/// into the method argument; we preserve the low 8 bits since
/// higher bits are unused on shipping titles. State transitions
/// (WAITING / DONE, pending) are applied by the commit pipeline
/// when it processes the emitted effect in batch N+1, preserving
/// the atomic-batch contract. The handler itself does NOT mutate
/// flip state because flip state lives on the runtime, not inside
/// the dispatch context.
pub fn nv4097_flip_buffer(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&arg) = args.first() {
        ctx.emitted.push(Effect::RsxFlipRequest {
            buffer_index: arg as u8,
        });
    }
}

/// Register the `GCM_FLIP_COMMAND` handler into `table`. Separate
/// helper because flip state and label / reference state are
/// distinct subsystems; callers that want one without the other
/// should not have to reason about the full set.
pub fn register_nv4097_flip_handler(
    table: &mut NvMethodTable,
) -> Result<(), DuplicateRegistration> {
    table.register_unique(GCM_FLIP_COMMAND, nv4097_flip_buffer)?;
    Ok(())
}

/// Mask for the report offset field packed into the
/// `NV4097_GET_REPORT` argument.
///
/// The method's single u32 argument is a report descriptor where
/// the low 24 bits encode a byte offset into the report region
/// and the upper bits encode a report type / location tag. Real
/// PS3 hardware has multiple report families distinguished by
/// that tag, and real titles reach their report slots through
/// label_base + (arg & 0x00FFFFFF). Our oracle widens this to
/// the full u32 so microtests that run without cellGcmInit
/// (label_base = 0) can target their own statics by absolute
/// address, matching the NV406E semaphore path's absolute-offset
/// semantics. Real titles set the upper bits to their report
/// type tag; those bits land in the effective address and, if
/// `label_base` is non-zero, they must encode a valid guest
/// address -- behavior the oracle does not currently guard.
/// Source: RPCS3's `Emu/RSX/rsx_methods.cpp` NV4097_SET_REPORT
/// handler.
pub const NV4097_REPORT_OFFSET_MASK: u32 = 0xFFFF_FFFF;
pub(crate) const NV4097_REPORT_OFFSET_MASK_U: u32 = NV4097_REPORT_OFFSET_MASK;

/// `NV4097_GET_REPORT` handler (Sony / PS3 libgcm refers to the
/// same method as `SetReport` from the guest-visible emit
/// perspective; RPCS3 uses the Nouveau-standard `GET_REPORT`
/// name for the register). Address `0x1800`.
///
/// Writes a 4-byte report payload at
/// `label_base + (arg & NV4097_REPORT_OFFSET_MASK)`. The payload
/// is the low 32 bits of the current guest-ticks clock --
/// deterministic across runs because GuestTicks advances by
/// `consumed_cost` per commit, which is itself deterministic.
/// The observable 16-byte report envelope (timestamp low / high /
/// value / type) is the shape retail titles poll (see RPCS3's
/// `Emu/RSX/rsx_methods.cpp` GET_REPORT handler). The oracle
/// currently writes only the 4-byte timestamp slot, which
/// exercises the label-write translation path; the report shape
/// can be widened when a title is observed reading the other
/// fields.
pub fn nv4097_get_report(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&arg) = args.first() {
        let offset = arg & NV4097_REPORT_OFFSET_MASK_U;
        let value = ctx.now.raw() as u32;
        ctx.emitted.push(Effect::RsxLabelWrite { offset, value });
    }
}

/// Register the `NV4097_GET_REPORT` handler into `table`.
pub fn register_nv4097_report_handler(
    table: &mut NvMethodTable,
) -> Result<(), DuplicateRegistration> {
    table.register_unique(NV4097_GET_REPORT, nv4097_get_report)?;
    Ok(())
}

/// Apply Sony's byte-0 / byte-2 pre-swap undo for
/// `BACK_END_WRITE_SEMAPHORE_RELEASE`. The inline
/// `cellGcmSetWriteBackEndLabel` pre-swaps bytes 0 and 2 before
/// emitting the method; real PS3 GPU swaps them back on the
/// write. The oracle reproduces the guest-visible outcome by
/// applying the same XOR-style swap to the incoming FIFO arg.
///
/// Factored as a `const fn` so the test assertions can compute
/// expected values without duplicating the bit math.
pub const fn back_end_semaphore_value_swap(value: u32) -> u32 {
    (value & 0xFF00_FF00) | ((value >> 16) & 0xFF) | (((value) & 0xFF) << 16)
}

/// `NV4097_SET_SEMAPHORE_OFFSET` handler. Behaves identically to
/// [`nv406e_semaphore_offset`] -- stores the arg into the
/// transient semaphore-offset register. Sony's inline
/// `cellGcmSetWriteBackEndLabel` emits this in tandem with
/// [`nv4097_back_end_write_semaphore_release`]. The oracle treats
/// the front-end / back-end variants as a single pool because it
/// does not model the NV pipeline stages; both write through the
/// same `sem_offset` register.
pub fn nv4097_set_semaphore_offset(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&offset) = args.first() {
        *ctx.sem_offset = offset;
    }
}

/// `NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE` handler. Emits an
/// [`Effect::RsxLabelWrite`] carrying the current `sem_offset`
/// and the byte-swapped release value (see
/// [`back_end_semaphore_value_swap`] for the rule).
pub fn nv4097_back_end_write_semaphore_release(ctx: &mut NvDispatchContext<'_>, args: &[u32]) {
    if let Some(&value) = args.first() {
        ctx.emitted.push(Effect::RsxLabelWrite {
            offset: *ctx.sem_offset,
            value: back_end_semaphore_value_swap(value),
        });
    }
}

/// Register the pair of back-end semaphore handlers. Separate
/// helper from the NV406E pair because the two paths have
/// distinct method addresses and distinct
/// semantics (back-end release applies the byte-swap).
pub fn register_nv4097_back_end_semaphore_handlers(
    table: &mut NvMethodTable,
) -> Result<(), DuplicateRegistration> {
    table.register_unique(NV4097_SET_SEMAPHORE_OFFSET, nv4097_set_semaphore_offset)?;
    table.register_unique(
        NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE,
        nv4097_back_end_write_semaphore_release,
    )?;
    Ok(())
}

/// Method-address-keyed dispatch table.
///
/// Keyed on the 14-bit method byte address returned by
/// [`decode_header`]. Populated at runtime construction by the
/// `register_nv*` helpers in this module; unregistered method
/// addresses take the unknown-method fallback in the advance pass.
#[derive(Debug, Default)]
pub struct NvMethodTable {
    handlers: BTreeMap<u16, NvMethodHandler>,
}

/// Error returned by [`NvMethodTable::register_unique`] when a handler
/// is already registered for the same method address. Carries both
/// the conflicting method id (so the caller's init log line names
/// the collision) and the prior handler pointer (so the caller can
/// inspect or restore it).
// PartialEq / Eq intentionally not derived: comparing fn pointers
// is unpredictable (codegen units may assign the same address to
// different functions, or different addresses to semantically
// identical zero-sized fn items). Callers that need to act on a
// collision should inspect the `method` field for the address and
// log `prior` as a pointer for diagnostics only.
#[derive(Debug, Clone, Copy)]
pub struct DuplicateRegistration {
    /// Method address that the failing registration targeted.
    pub method: u16,
    /// Handler that was already registered at `method`. Preserved
    /// in the table; the failing registration's handler is NOT
    /// stored.
    pub prior: NvMethodHandler,
}

impl NvMethodTable {
    /// Construct an empty dispatch table.
    #[inline]
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a handler for the given method address. Returns any
    /// previously-registered handler.
    ///
    /// This variant silently replaces a prior handler at the same
    /// method address. If you want a registration-time collision to
    /// be surfaced, call [`Self::register_unique`] instead.
    ///
    /// Registering a handler at address `0x0000` will fire on every
    /// NOP (Sony: `CELL_GCM_METHOD_NOP = 0x00000000`). NOPs appear
    /// in real FIFO streams as alignment padding at command-buffer
    /// boundaries and can occur millions of times per frame;
    /// registering a handler there is almost certainly a bug.
    #[inline]
    pub fn register(&mut self, method: u16, handler: NvMethodHandler) -> Option<NvMethodHandler> {
        self.handlers.insert(method, handler)
    }

    /// Register a handler that is expected to be the first at this
    /// method address. Returns [`DuplicateRegistration`] on
    /// collision, carrying the method id and the existing handler
    /// -- meaning the caller's init sequence has a duplicate
    /// registration bug.
    ///
    /// Prefer this at startup / bootstrap registration; a silent
    /// collision on the fixed handler set is a real bug and should
    /// fail loudly rather than get papered over.
    /// The error's `method` field supplies the id so the caller's
    /// panic / log message can name the offending method without
    /// re-looking-up.
    ///
    /// On collision, the table is NOT mutated: the prior handler
    /// remains in place and the new handler is discarded.
    ///
    /// Registering at `0x0000` carries the same caveat as
    /// [`Self::register`]; see that method's doc.
    #[inline]
    pub fn register_unique(
        &mut self,
        method: u16,
        handler: NvMethodHandler,
    ) -> Result<(), DuplicateRegistration> {
        if let Some(&prior) = self.handlers.get(&method) {
            Err(DuplicateRegistration { method, prior })
        } else {
            self.handlers.insert(method, handler);
            Ok(())
        }
    }

    /// Look up the handler registered for `method`, if any. Returns
    /// `None` if the method is not registered -- the advance pass
    /// treats `None` as the unknown-method fallback.
    #[inline]
    pub fn lookup(&self, method: u16) -> Option<NvMethodHandler> {
        self.handlers.get(&method).copied()
    }

    /// Number of registered handlers.
    #[inline]
    pub fn len(&self) -> usize {
        self.handlers.len()
    }

    /// Whether the table has any registered handlers.
    #[inline]
    pub fn is_empty(&self) -> bool {
        self.handlers.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hdr(cmd: u32) -> NvMethodHeader {
        decode_header(cmd)
    }

    // Mask both fields so a typo cannot silently set a control-flow flag bit.
    fn method_header(method: u32, count: u32) -> u32 {
        ((count & NV_COUNT_MASK_11) << NV_COUNT_SHIFT) | (method & NV_METHOD_MASK)
    }

    fn method_header_ni(method: u32, count: u32) -> u32 {
        method_header(method, count) | NV_FLAG_NON_INCREMENT
    }

    #[test]
    fn nop_is_zero_count_increment() {
        let h = hdr(0x0000_0000);
        assert_eq!(h, NvMethodHeader::normal(NvCommandKind::Increment, 0, 0));
    }

    #[test]
    fn increment_normal_method() {
        let h = hdr(method_header(NV406E_SET_REFERENCE as u32, 1));
        assert_eq!(h.kind, NvCommandKind::Increment);
        assert_eq!(h.method, NV406E_SET_REFERENCE);
        assert_eq!(h.count, 1);
    }

    #[test]
    fn increment_semaphore_pair() {
        let off = hdr(method_header(NV406E_SEMAPHORE_OFFSET as u32, 1));
        let rel = hdr(method_header(NV406E_SEMAPHORE_RELEASE as u32, 1));
        assert_eq!(off.method, 0x0064);
        assert_eq!(rel.method, 0x006C);
        assert_eq!(off.count, 1);
        assert_eq!(rel.count, 1);
    }

    #[test]
    fn non_increment_method() {
        let h = hdr(method_header_ni(0x1818, 32));
        assert_eq!(h.kind, NvCommandKind::NonIncrement);
        assert_eq!(h.method, 0x1818);
        assert_eq!(h.count, 32);
    }

    #[test]
    fn count_field_spans_11_bits() {
        let h = hdr(method_header(0x0100, 2047));
        assert_eq!(h.count, 2047);
        let h = hdr(method_header(0x0100, 0x7FF));
        assert_eq!(h.count, 0x7FF);
    }

    #[test]
    fn method_address_preserves_subchannel_bits() {
        let h = hdr(method_header(GCM_FLIP_COMMAND as u32, 1));
        assert_eq!(h.method, 0xFEAC);
    }

    #[test]
    fn method_address_zero_in_low_bits() {
        let raw = method_header(0x0053, 1);
        let h = hdr(raw);
        assert_eq!(h.method, 0x0050, "low 2 bits masked off");
    }

    #[test]
    fn old_jump_decodes() {
        let h = hdr(0x2000_1000 | NV_FLAG_JUMP);
        assert_eq!(h.kind, NvCommandKind::Jump { offset: 0x1000 });
        let h = hdr(NV_FLAG_JUMP | 0x0004_0000);
        assert_eq!(
            h.kind,
            NvCommandKind::Jump {
                offset: 0x0004_0000
            }
        );
    }

    #[test]
    fn old_jump_maximum_offset_fits_29_bits() {
        let h = hdr(NV_FLAG_JUMP | 0x1FFF_FFFC);
        assert_eq!(
            h.kind,
            NvCommandKind::Jump {
                offset: 0x1FFF_FFFC
            }
        );
    }

    #[test]
    fn old_jump_with_bit_31_set_is_malformed() {
        let h = hdr(0x8000_0000 | NV_FLAG_JUMP);
        match h.kind {
            NvCommandKind::Malformed { .. } => {}
            other => panic!("expected Malformed, got {:?}", other),
        }
    }

    #[test]
    fn new_jump_decodes() {
        let h = hdr(NV_FLAG_NEW_JUMP | 0x0003_0000);
        assert_eq!(
            h.kind,
            NvCommandKind::NewJump {
                offset: 0x0003_0000
            }
        );
    }

    #[test]
    fn call_decodes() {
        let h = hdr(NV_FLAG_CALL | 0x0010_1000);
        assert_eq!(
            h.kind,
            NvCommandKind::Call {
                offset: 0x0010_1000
            }
        );
    }

    #[test]
    fn return_decodes() {
        let h = hdr(NV_FLAG_RETURN);
        assert_eq!(h.kind, NvCommandKind::Return);
    }

    #[test]
    fn return_with_extra_bits_is_malformed() {
        let h = hdr(NV_FLAG_RETURN | 0x0004_0000);
        match h.kind {
            NvCommandKind::Malformed { raw } => {
                assert_eq!(raw, NV_FLAG_RETURN | 0x0004_0000);
            }
            _ => panic!("expected Malformed, got {:?}", h.kind),
        }
    }

    #[test]
    fn malformed_with_bit_31_set() {
        let h = hdr(0x8000_0000);
        match h.kind {
            NvCommandKind::Malformed { raw } => assert_eq!(raw, 0x8000_0000),
            _ => panic!("expected Malformed"),
        }
    }

    #[test]
    fn malformed_with_reserved_bit_16_set() {
        let h = hdr(0x0001_0000);
        match h.kind {
            NvCommandKind::Malformed { raw } => assert_eq!(raw, 0x0001_0000),
            _ => panic!("expected Malformed"),
        }
    }

    #[test]
    fn jump_plus_new_jump_is_malformed() {
        let h = hdr(NV_FLAG_JUMP | NV_FLAG_NEW_JUMP);
        match h.kind {
            NvCommandKind::Malformed { .. } => {}
            other => panic!("expected Malformed, got {:?}", other),
        }
    }

    #[test]
    fn return_plus_call_decodes_as_call_per_hardware() {
        let h = hdr(NV_FLAG_RETURN | NV_FLAG_CALL);
        match h.kind {
            NvCommandKind::Call { offset } => {
                assert_eq!(offset, NV_FLAG_RETURN & NV_CALL_OFFSET_MASK);
            }
            other => panic!("expected Call, got {:?}", other),
        }
    }

    #[test]
    fn return_plus_new_jump_decodes_as_new_jump_per_hardware() {
        let h = hdr(NV_FLAG_RETURN | NV_FLAG_NEW_JUMP);
        match h.kind {
            NvCommandKind::NewJump { offset } => {
                assert_eq!(offset, NV_FLAG_RETURN & NV_NEW_JUMP_OFFSET_MASK);
            }
            other => panic!("expected NewJump, got {:?}", other),
        }
    }

    #[test]
    fn call_with_bit_31_set_decodes_as_call_per_hardware() {
        let h = hdr(0x8000_0000 | NV_FLAG_CALL);
        match h.kind {
            NvCommandKind::Call { offset } => {
                assert_eq!(offset, 0);
            }
            other => panic!("expected Call, got {:?}", other),
        }
    }

    #[test]
    fn call_with_jump_flag_decodes_as_call_per_hardware() {
        let h = hdr(NV_FLAG_JUMP | NV_FLAG_CALL);
        match h.kind {
            NvCommandKind::Call { offset } => {
                assert_eq!(offset, NV_FLAG_JUMP & NV_CALL_OFFSET_MASK);
            }
            other => panic!("expected Call, got {:?}", other),
        }
    }

    #[test]
    fn bit_31_alone_is_malformed() {
        let h = hdr(0x8000_0000);
        match h.kind {
            NvCommandKind::Malformed { raw } => assert_eq!(raw, 0x8000_0000),
            other => panic!("expected Malformed, got {:?}", other),
        }
    }

    #[test]
    fn return_bit_with_stray_method_is_malformed() {
        let h = hdr(NV_FLAG_RETURN | 0x0000_0050);
        match h.kind {
            NvCommandKind::Malformed { raw } => {
                assert_eq!(raw, NV_FLAG_RETURN | 0x0000_0050);
            }
            other => panic!("expected Malformed, got {:?}", other),
        }
    }

    #[test]
    fn table_new_is_empty() {
        let t = NvMethodTable::new();
        assert_eq!(t.len(), 0);
        assert!(t.is_empty());
    }

    #[test]
    fn table_lookup_unregistered_method_returns_none() {
        let t = NvMethodTable::new();
        assert!(t.lookup(NV406E_SEMAPHORE_OFFSET).is_none());
        assert!(t.lookup(NV4097_GET_REPORT).is_none());
        assert!(t.lookup(GCM_FLIP_COMMAND).is_none());
    }

    fn fresh_state() -> (RsxFifoCursor, u32, Vec<Effect>) {
        (RsxFifoCursor::new(), 0u32, Vec::new())
    }

    fn ctx_for<'a>(
        cursor: &'a mut RsxFifoCursor,
        sem_offset: &'a mut u32,
        emitted: &'a mut Vec<Effect>,
    ) -> NvDispatchContext<'a> {
        NvDispatchContext {
            cursor,
            sem_offset,
            emitted,
            now: GuestTicks::ZERO,
        }
    }

    fn noop_handler(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {}

    #[test]
    fn table_register_inserts_and_returns_none_on_fresh_slot() {
        let mut t = NvMethodTable::new();
        let prior = t.register(NV406E_SEMAPHORE_OFFSET, noop_handler);
        assert!(prior.is_none());
        assert_eq!(t.len(), 1);
        assert!(t.lookup(NV406E_SEMAPHORE_OFFSET).is_some());
    }

    #[test]
    fn table_register_replaces_prior_handler() {
        fn handler_a(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {}
        fn handler_b(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {}
        let mut t = NvMethodTable::new();
        t.register(NV406E_SEMAPHORE_OFFSET, handler_a);
        let prior = t.register(NV406E_SEMAPHORE_OFFSET, handler_b);
        assert!(prior.is_some());
        assert_eq!(t.len(), 1, "same slot replaced, not appended");
    }

    #[test]
    fn table_register_unique_succeeds_on_fresh_slot() {
        let mut t = NvMethodTable::new();
        let result = t.register_unique(NV406E_SEMAPHORE_OFFSET, noop_handler);
        assert!(result.is_ok());
        assert_eq!(t.len(), 1);
    }

    #[test]
    fn table_register_unique_fails_on_collision_with_method_id() {
        fn handler_a(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {}
        fn handler_b(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {}
        let mut t = NvMethodTable::new();
        t.register_unique(NV406E_SEMAPHORE_OFFSET, handler_a)
            .unwrap();
        let err = t
            .register_unique(NV406E_SEMAPHORE_OFFSET, handler_b)
            .expect_err("collision must surface");
        assert_eq!(
            err.method, NV406E_SEMAPHORE_OFFSET,
            "error carries the offending method id"
        );
        assert_eq!(t.len(), 1, "failed unique-registration does not mutate");
    }

    // Reset TRUN_*_CALLS before each test that reuses trun_*_handler.
    use std::sync::atomic::{AtomicU32, Ordering};
    static TRUN_A_CALLS: AtomicU32 = AtomicU32::new(0);
    static TRUN_B_CALLS: AtomicU32 = AtomicU32::new(0);
    fn trun_a_handler(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {
        TRUN_A_CALLS.fetch_add(1, Ordering::SeqCst);
    }
    fn trun_b_handler(_ctx: &mut NvDispatchContext<'_>, _args: &[u32]) {
        TRUN_B_CALLS.fetch_add(1, Ordering::SeqCst);
    }

    #[test]
    fn table_register_unique_does_not_overwrite_on_failure() {
        // Side-channel check: a lookup-returns-Some assertion would
        // pass even if the overwrite had succeeded, so observe which
        // handler actually fires via its counter.
        TRUN_A_CALLS.store(0, Ordering::SeqCst);
        TRUN_B_CALLS.store(0, Ordering::SeqCst);

        let mut t = NvMethodTable::new();
        t.register_unique(NV406E_SEMAPHORE_OFFSET, trun_a_handler)
            .unwrap();
        let _ = t.register_unique(NV406E_SEMAPHORE_OFFSET, trun_b_handler);

        let h = t
            .lookup(NV406E_SEMAPHORE_OFFSET)
            .expect("handler still registered");
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        h(&mut ctx, &[]);

        assert_eq!(
            TRUN_A_CALLS.load(Ordering::SeqCst),
            1,
            "handler_a fired (prior handler preserved)"
        );
        assert_eq!(
            TRUN_B_CALLS.load(Ordering::SeqCst),
            0,
            "handler_b did NOT fire (overwrite attempted and rejected)"
        );
    }

    // --- NV406E semaphore handlers ---

    #[test]
    fn nv406e_semaphore_offset_stores_arg_into_sem_offset() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_semaphore_offset(&mut ctx, &[0x1234_5678]);
        assert_eq!(sem_offset, 0x1234_5678);
        assert!(emitted.is_empty(), "offset handler emits nothing");
    }

    #[test]
    fn nv406e_semaphore_offset_noop_on_empty_args() {
        let mut cursor = RsxFifoCursor::new();
        let mut sem_offset: u32 = 0xDEAD_BEEF;
        let mut emitted: Vec<Effect> = Vec::new();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_semaphore_offset(&mut ctx, &[]);
        assert_eq!(sem_offset, 0xDEAD_BEEF);
    }

    #[test]
    fn nv406e_semaphore_release_emits_label_write_with_current_offset() {
        let mut cursor = RsxFifoCursor::new();
        let mut sem_offset: u32 = 0x80;
        let mut emitted: Vec<Effect> = Vec::new();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_semaphore_release(&mut ctx, &[0xAABB_CCDD]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0x80,
                value: 0xAABB_CCDD,
            }]
        );
    }

    #[test]
    fn nv406e_semaphore_release_noop_on_empty_args() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_semaphore_release(&mut ctx, &[]);
        assert!(emitted.is_empty());
    }

    #[test]
    fn nv406e_offset_release_pair_threads_offset_through_emitted_write() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_semaphore_offset(&mut ctx, &[0x100]);
        nv406e_semaphore_release(&mut ctx, &[42]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0x100,
                value: 42,
            }]
        );
    }

    #[test]
    fn nv406e_release_without_prior_offset_uses_current_sem_offset() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_semaphore_release(&mut ctx, &[9]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0,
                value: 9,
            }]
        );
    }

    // --- NV406E_SET_REFERENCE handler ---

    #[test]
    fn nv406e_set_reference_stores_arg_into_cursor_current_reference() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_set_reference(&mut ctx, &[0xCAFE_BABE]);
        assert_eq!(cursor.current_reference(), 0xCAFE_BABE);
        assert_eq!(sem_offset, 0, "reference handler must not touch sem_offset");
        assert!(emitted.is_empty(), "reference handler emits no effect");
    }

    #[test]
    fn nv406e_set_reference_noop_on_empty_args() {
        let mut cursor = RsxFifoCursor::new();
        cursor.set_reference(0xDEAD_BEEF);
        let mut sem_offset = 0u32;
        let mut emitted: Vec<Effect> = Vec::new();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_set_reference(&mut ctx, &[]);
        assert_eq!(cursor.current_reference(), 0xDEAD_BEEF);
    }

    #[test]
    fn nv406e_set_reference_overwrites_prior_reference() {
        let mut cursor = RsxFifoCursor::new();
        cursor.set_reference(0x1111);
        let mut sem_offset = 0u32;
        let mut emitted: Vec<Effect> = Vec::new();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv406e_set_reference(&mut ctx, &[0x2222]);
        assert_eq!(
            cursor.current_reference(),
            0x2222,
            "later SET_REFERENCE overwrites earlier one; Sony reference semantics are last-writer-wins"
        );
    }

    // --- NV4097 GCM_FLIP_COMMAND handler ---

    #[test]
    fn nv4097_flip_buffer_emits_rsx_flip_request_with_buffer_index() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_flip_buffer(&mut ctx, &[3]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxFlipRequest { buffer_index: 3 }]
        );
    }

    #[test]
    fn nv4097_flip_buffer_truncates_large_arg_to_buffer_index_byte() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_flip_buffer(&mut ctx, &[0x1234_56FF]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxFlipRequest { buffer_index: 0xFF }]
        );
    }

    #[test]
    fn nv4097_flip_buffer_noop_on_empty_args() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_flip_buffer(&mut ctx, &[]);
        assert!(emitted.is_empty());
    }

    // --- NV4097 GET_REPORT handler ---

    fn ctx_with_time<'a>(
        cursor: &'a mut RsxFifoCursor,
        sem_offset: &'a mut u32,
        emitted: &'a mut Vec<Effect>,
        now: GuestTicks,
    ) -> NvDispatchContext<'a> {
        NvDispatchContext {
            cursor,
            sem_offset,
            emitted,
            now,
        }
    }

    #[test]
    fn nv4097_get_report_emits_label_write_at_arg_offset() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_with_time(
            &mut cursor,
            &mut sem_offset,
            &mut emitted,
            GuestTicks::new(0x1234),
        );
        let report_arg = 0x0100_0040u32;
        nv4097_get_report(&mut ctx, &[report_arg]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0x0100_0040,
                value: 0x1234,
            }]
        );
    }

    #[test]
    fn nv4097_get_report_uses_guest_ticks_as_value() {
        fn emit_with_time(ticks: u64) -> u32 {
            let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
            let mut ctx = ctx_with_time(
                &mut cursor,
                &mut sem_offset,
                &mut emitted,
                GuestTicks::new(ticks),
            );
            nv4097_get_report(&mut ctx, &[0x0u32]);
            match emitted[0] {
                Effect::RsxLabelWrite { value, .. } => value,
                _ => panic!("expected RsxLabelWrite"),
            }
        }
        assert_eq!(emit_with_time(0), 0);
        assert_eq!(emit_with_time(1_000), 1_000);
        // Truncation to low 32 bits is the oracle's timestamp-slot contract.
        assert_eq!(emit_with_time(0x1_0000_0001), 1);
    }

    #[test]
    fn nv4097_get_report_passes_full_u32_as_offset() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_with_time(
            &mut cursor,
            &mut sem_offset,
            &mut emitted,
            GuestTicks::new(7),
        );
        nv4097_get_report(&mut ctx, &[0xFF12_3456u32]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0xFF12_3456,
                value: 7,
            }]
        );
    }

    #[test]
    fn nv4097_get_report_noop_on_empty_args() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_with_time(
            &mut cursor,
            &mut sem_offset,
            &mut emitted,
            GuestTicks::new(5),
        );
        nv4097_get_report(&mut ctx, &[]);
        assert!(emitted.is_empty());
    }

    #[test]
    fn register_nv4097_report_handler_inserts_address() {
        let mut t = NvMethodTable::new();
        register_nv4097_report_handler(&mut t).expect("fresh table");
        assert!(t.lookup(NV4097_GET_REPORT).is_some());
        assert_eq!(t.len(), 1);
    }

    #[test]
    fn register_nv4097_report_handler_surfaces_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(NV4097_GET_REPORT, noop_handler).unwrap();
        let err = register_nv4097_report_handler(&mut t)
            .expect_err("pre-existing registration must collide");
        assert_eq!(err.method, NV4097_GET_REPORT);
    }

    // --- NV4097 back-end semaphore handlers ---

    #[test]
    fn back_end_semaphore_value_swap_is_its_own_inverse() {
        for sample in [
            0x0000_0000u32,
            0xFFFF_FFFFu32,
            0x1122_3344u32,
            0xAA00_BBFFu32,
            0x1234_5678u32,
        ] {
            assert_eq!(
                back_end_semaphore_value_swap(back_end_semaphore_value_swap(sample)),
                sample,
                "swap is involutive on {sample:#010x}"
            );
        }
    }

    #[test]
    fn back_end_semaphore_value_swap_exchanges_bytes_0_and_2() {
        assert_eq!(
            back_end_semaphore_value_swap(0x1122_3344),
            0x1144_3322,
            "bytes: [11 22 33 44] -> [11 44 33 22]"
        );
    }

    #[test]
    fn nv4097_set_semaphore_offset_stores_arg() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_set_semaphore_offset(&mut ctx, &[0x1234_5678]);
        assert_eq!(sem_offset, 0x1234_5678);
        assert!(emitted.is_empty());
    }

    #[test]
    fn nv4097_set_semaphore_offset_noop_on_empty_args() {
        let mut cursor = RsxFifoCursor::new();
        let mut sem_offset = 0xDEAD_BEEFu32;
        let mut emitted: Vec<Effect> = Vec::new();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_set_semaphore_offset(&mut ctx, &[]);
        assert_eq!(sem_offset, 0xDEAD_BEEF);
    }

    #[test]
    fn nv4097_back_end_release_emits_label_write_with_byte_swap() {
        let mut cursor = RsxFifoCursor::new();
        let mut sem_offset: u32 = 0x20;
        let mut emitted: Vec<Effect> = Vec::new();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        // fifo_arg is the already-pre-swapped value the guest wrote.
        let fifo_arg = 0x1144_3322u32;
        nv4097_back_end_write_semaphore_release(&mut ctx, &[fifo_arg]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0x20,
                value: 0x1122_3344,
            }]
        );
    }

    #[test]
    fn nv4097_back_end_release_noop_on_empty_args() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_back_end_write_semaphore_release(&mut ctx, &[]);
        assert!(emitted.is_empty());
    }

    #[test]
    fn nv4097_back_end_pair_threads_offset_through_emitted_write_post_swap() {
        let (mut cursor, mut sem_offset, mut emitted) = fresh_state();
        let mut ctx = ctx_for(&mut cursor, &mut sem_offset, &mut emitted);
        nv4097_set_semaphore_offset(&mut ctx, &[0x10]);
        // 0xAADD_CCBB is the pre-swap of 0xAABB_CCDD.
        nv4097_back_end_write_semaphore_release(&mut ctx, &[0xAADD_CCBB]);
        assert_eq!(
            emitted.as_slice(),
            &[Effect::RsxLabelWrite {
                offset: 0x10,
                value: 0xAABB_CCDD,
            }]
        );
    }

    #[test]
    fn register_nv4097_back_end_semaphore_handlers_inserts_both_addresses() {
        let mut t = NvMethodTable::new();
        register_nv4097_back_end_semaphore_handlers(&mut t).expect("fresh table");
        assert!(t.lookup(NV4097_SET_SEMAPHORE_OFFSET).is_some());
        assert!(t.lookup(NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE).is_some());
        assert_eq!(t.len(), 2);
    }

    #[test]
    fn register_nv4097_back_end_semaphore_handlers_surfaces_offset_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(NV4097_SET_SEMAPHORE_OFFSET, noop_handler)
            .unwrap();
        let err = register_nv4097_back_end_semaphore_handlers(&mut t)
            .expect_err("pre-existing OFFSET registration must collide");
        assert_eq!(err.method, NV4097_SET_SEMAPHORE_OFFSET);
        assert!(t.lookup(NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE).is_none());
    }

    #[test]
    fn register_nv4097_back_end_semaphore_handlers_surfaces_release_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE, noop_handler)
            .unwrap();
        let err = register_nv4097_back_end_semaphore_handlers(&mut t)
            .expect_err("pre-existing RELEASE registration must collide");
        assert_eq!(err.method, NV4097_BACK_END_WRITE_SEMAPHORE_RELEASE);
    }

    #[test]
    fn register_nv4097_flip_handler_inserts_address() {
        let mut t = NvMethodTable::new();
        register_nv4097_flip_handler(&mut t).expect("fresh table");
        assert!(t.lookup(GCM_FLIP_COMMAND).is_some());
        assert_eq!(t.len(), 1);
    }

    #[test]
    fn register_nv4097_flip_handler_surfaces_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(GCM_FLIP_COMMAND, noop_handler).unwrap();
        let err = register_nv4097_flip_handler(&mut t)
            .expect_err("pre-existing registration must collide");
        assert_eq!(err.method, GCM_FLIP_COMMAND);
    }

    #[test]
    fn register_nv406e_reference_handler_inserts_address() {
        let mut t = NvMethodTable::new();
        register_nv406e_reference_handler(&mut t).expect("fresh table");
        assert!(t.lookup(NV406E_SET_REFERENCE).is_some());
        assert_eq!(t.len(), 1);
    }

    #[test]
    fn register_nv406e_reference_handler_surfaces_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(NV406E_SET_REFERENCE, noop_handler)
            .unwrap();
        let err = register_nv406e_reference_handler(&mut t)
            .expect_err("pre-existing registration must collide");
        assert_eq!(err.method, NV406E_SET_REFERENCE);
    }

    #[test]
    fn register_nv406e_label_handlers_inserts_both_addresses() {
        let mut t = NvMethodTable::new();
        register_nv406e_label_handlers(&mut t).expect("fresh table");
        assert!(t.lookup(NV406E_SEMAPHORE_OFFSET).is_some());
        assert!(t.lookup(NV406E_SEMAPHORE_RELEASE).is_some());
        assert_eq!(t.len(), 2);
    }

    #[test]
    fn register_nv406e_label_handlers_surfaces_offset_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(NV406E_SEMAPHORE_OFFSET, noop_handler)
            .unwrap();
        let err = register_nv406e_label_handlers(&mut t)
            .expect_err("OFFSET already present must collide");
        assert_eq!(err.method, NV406E_SEMAPHORE_OFFSET);
        assert!(t.lookup(NV406E_SEMAPHORE_RELEASE).is_none());
    }

    #[test]
    fn register_nv406e_label_handlers_surfaces_release_collision() {
        let mut t = NvMethodTable::new();
        t.register_unique(NV406E_SEMAPHORE_RELEASE, noop_handler)
            .unwrap();
        let err = register_nv406e_label_handlers(&mut t)
            .expect_err("RELEASE already present must collide");
        assert_eq!(err.method, NV406E_SEMAPHORE_RELEASE);
        // Offset registers before the release collision, so it
        // remains in the table. The helper is not all-or-nothing.
        assert!(t.lookup(NV406E_SEMAPHORE_OFFSET).is_some());
    }

    #[test]
    fn nv_constant_values_pin_rpcs3_lineage() {
        assert_eq!(NV406E_SET_REFERENCE, 0x0050);
        assert_eq!(NV406E_SEMAPHORE_OFFSET, 0x0064);
        assert_eq!(NV406E_SEMAPHORE_ACQUIRE, 0x0068);
        assert_eq!(NV406E_SEMAPHORE_RELEASE, 0x006C);
        assert_eq!(NV4097_NO_OPERATION, 0x0100);
        assert_eq!(NV4097_GET_REPORT, 0x1800);
        assert_eq!(GCM_FLIP_COMMAND, 0xFEAC);
        assert_eq!(NV_FLAG_NON_INCREMENT, 0x4000_0000);
        assert_eq!(NV_FLAG_JUMP, 0x2000_0000);
        assert_eq!(NV_FLAG_CALL, 0x0000_0002);
        assert_eq!(NV_FLAG_RETURN, 0x0002_0000);
        assert_eq!(NV_COUNT_SHIFT, 18);
    }
}
