[package]
name = "cellgov_lv2_archive"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
cellgov_lv2 = { path = "../cellgov_lv2" }
cellgov_ps3_abi = { path = "../cellgov_ps3_abi" }
thiserror = "2"
strum = { version = "0.26", default-features = false }

[dev-dependencies]
cellgov_event = { path = "../cellgov_event" }
cellgov_mem = { path = "../cellgov_mem" }
cellgov_time = { path = "../cellgov_time" }
sha2 = "0.10"
